In [13]:
import numpy as np
import math

from mandelbrot import mandelbrot_generator


def get_escape_time(c: complex, max_iterations: int) -> int | None:
    """Returns the escape time of a mandelbrot sequence with initial term c

    Parameters:
        c [complex]: the initial term
        max_iterations [int]: the maximum number of iterations

    Returns:
        int: the number of iterations within max_iterations for |z_n| > 2
        None: if |z_n| <= 2 for n = max_iterations

    """
    if abs(mandelbrot_generator(c,max_iterations)) <= 2:
        return None
    else:
        for i in range(max_iterations + 1):
            if abs(mandelbrot_generator(c,i)) > 2:
                return i


print(get_escape_time(2+1j, 5))
print(get_escape_time(1+1j, 10))
print(get_escape_time(0.5+0.5j, 3))
print(get_escape_time(0.5+0.5j, 4))
print(get_escape_time(0.38+0.25j, 100))



0
1
None
4
56


In [12]:
def mandelbrot_generator(x: complex, y: int) -> complex:
        """Generates the y'th term of the mandelbrot sequence with initial term x

        Parameters:
            x [complex]: the initial term
            y [int]: the term to generate

        Returns:
            complex: the y'th term of the mandelbrot sequence

        """

        if y == 0:
            return x
        else:
            return mandelbrot_generator(x, y-1) ** 2 + x

mandelbrot_generator(-2,11)

2

In [27]:
def get_complex_grid(top_left = complex, bottom_right = complex, step = float) -> np.ndarray:

    x1 = top_left.real
    x2 = bottom_right.real
    y1 = top_left.imag
    y2 = bottom_right.imag

    m = math.floor(x2 - x1)
    n = math.floor(y1 - y2)
    array = np.zeros((n+1, m+1))
    array[0,0] = top_left

    imag_vect = np.arange(n+1).reshape(n+1,1)
    imag_vect = imag_vect * step
    imag_vect = imag_vect * -1
    real_vect = np.arange(n+1) * step

    grid_step = real_vect + imag_vect
    return array + grid_step

print(get_complex_grid(0, 3 - 3j, 1))




[[ 0.  1.  2.  3.]
 [-1.  0.  1.  2.]
 [-2. -1.  0.  1.]
 [-3. -2. -1.  0.]]
